"use client";

import { useEffect, useState } from "react";
import { Loader2, LayoutTemplate, Settings, Code, Layers } from "lucide-react";

interface BuilderComponent {
  id: number;
  type: string;
  name: string;
  props: Record<string, any>;
  sortOrder: number;
}

// ── Dynamic Component Registry ─────────────────────────────────────────────
// The Visual Builder maps the 'type' string from the database to actual React nodes.

const NavbarComponent = ({ props }: { props: any }) => (
  <nav className="w-full bg-white border-b border-slate-200 px-6 py-4 flex items-center justify-between shadow-sm">
    <div className="font-bold text-bnlv-navy text-lg">{props.title || "Brand Logo"}</div>
    <div className="space-x-4 text-sm text-slate-600 font-medium">
      <a href="#" className="hover:text-bnlv-gold transition-colors">Home</a>
      <a href="#" className="hover:text-bnlv-gold transition-colors">Features</a>
      <a href="#" className="hover:text-bnlv-gold transition-colors">Contact</a>
    </div>
  </nav>
);

const HeroComponent = ({ props }: { props: any }) => (
  <div className="w-full bg-slate-50 py-24 px-8 text-center border-b border-slate-200">
    <h1 className="text-4xl font-extrabold text-slate-900 tracking-tight mb-4">
      {props.title || "Generated Hero Title"}
    </h1>
    <p className="text-lg text-slate-600 max-w-2xl mx-auto">
      {props.content || "This content was generated by the AI autonomous engine and saved directly into the builder component parameters."}
    </p>
    <button className="mt-8 px-6 py-3 bg-bnlv-navy text-white rounded-lg shadow-sm hover:bg-slate-800 transition-colors font-medium">
      Get Started
    </button>
  </div>
);

const DefaultComponent = ({ type }: { type: string }) => (
  <div className="w-full p-8 border-2 border-dashed border-slate-300 rounded-lg text-center bg-slate-50 text-slate-500">
    <Layers className="w-8 h-8 mx-auto mb-2 text-slate-400" />
    Unknown Component Type: <span className="font-mono font-medium text-slate-700">{type}</span>
  </div>
);

const renderComponent = (comp: BuilderComponent) => {
  switch (comp.type) {
    case "navbar": return <NavbarComponent props={comp.props} />;
    case "hero": return <HeroComponent props={comp.props} />;
    default: return <DefaultComponent type={comp.type} />;
  }
};

// ─────────────────────────────────────────────────────────────────────────────

export default function VisualBuilder() {
  const [components, setComponents] = useState<BuilderComponent[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  
  // Hardcoded for demonstration. In a real app, this comes from URL params or context.
  const ACTIVE_PROJECT_ID = 1; 

  useEffect(() => {
    const fetchComponents = async () => {
      try {
        const res = await fetch(`/api/projects/${ACTIVE_PROJECT_ID}/components`);
        const json = await res.json();
        if (json.data) setComponents(json.data);
      } catch (error) {
        console.error("Failed to fetch builder components:", error);
      } finally {
        setIsLoading(false);
      }
    };
    fetchComponents();
  }, []);

  if (isLoading) {
    return (
      <div className="p-8 flex items-center justify-center text-sm text-slate-500 h-full min-h-[400px]">
        <Loader2 className="w-5 h-5 animate-spin mr-2" /> Syncing Visual Builder Canvas...
      </div>
    );
  }

  return (
    <div className="flex h-[calc(100vh-4rem)] bg-slate-100 overflow-hidden">
      
      {/* LEFT: Sidebar / Layers Panel */}
      <div className="w-64 bg-white border-r border-slate-200 flex flex-col h-full shrink-0">
        <div className="p-4 border-b border-slate-200 flex items-center text-slate-900 font-semibold">
          <LayoutTemplate className="w-5 h-5 mr-2 text-bnlv-navy" />
          Page Layers
        </div>
        <div className="p-4 space-y-2 overflow-y-auto flex-1">
          {components.map((comp) => (
            <div key={comp.id} className="flex items-center justify-between p-2 rounded-md hover:bg-slate-50 border border-transparent hover:border-slate-200 transition-all cursor-pointer group">
              <div className="flex items-center space-x-2 truncate">
                <Code className="w-4 h-4 text-slate-400" />
                <span className="text-sm font-medium text-slate-700 truncate">{comp.name}</span>
              </div>
              <Settings className="w-4 h-4 text-slate-300 opacity-0 group-hover:opacity-100 transition-opacity" />
            </div>
          ))}
          {components.length === 0 && (
            <p className="text-xs text-slate-500 text-center py-4">No components provisioned yet.</p>
          )}
        </div>
      </div>

      {/* RIGHT: Live Rendering Canvas */}
      <div className="flex-1 overflow-y-auto relative">
        <div className="max-w-5xl mx-auto my-8 bg-white shadow-xl ring-1 ring-slate-900/5 min-h-[800px] flex flex-col relative overflow-hidden">
          {/* Canvas Toolbar */}
          <div className="absolute top-0 left-0 w-full h-8 bg-slate-800 flex items-center px-4 space-x-2 z-10 rounded-t-sm">
             <div className="w-3 h-3 rounded-full bg-red-400"></div>
             <div className="w-3 h-3 rounded-full bg-yellow-400"></div>
             <div className="w-3 h-3 rounded-full bg-green-400"></div>
             <span className="text-xs text-slate-400 font-mono ml-4">bnlv-studio-preview</span>
          </div>

          {/* Canvas Render Area */}
          <div className="pt-8 flex-1 flex flex-col">
            {components.length === 0 ? (
              <div className="flex-1 flex flex-col items-center justify-center text-slate-400">
                <Layers className="w-12 h-12 mb-4 opacity-50" />
                <p className="text-sm">Canvas is empty. Submit a prompt to the AI Engine to begin.</p>
              </div>
            ) : (
              components.map((comp) => (
                <div key={comp.id} className="relative group hover:ring-2 hover:ring-bnlv-navy/50 transition-all">
                  {/* Hover Overlay Label */}
                  <div className="absolute -top-3 left-2 bg-bnlv-navy text-white text-[10px] px-2 py-0.5 rounded opacity-0 group-hover:opacity-100 z-20 pointer-events-none">
                    {comp.type}
                  </div>
                  {renderComponent(comp)}
                </div>
              ))
            )}
          </div>
        </div>
      </div>
      
    </div>
  );
}